# Generated by Django 2.2 on 2019-05-01 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_choices',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='one', max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_choice', to='polls.Question'),
        ),
    ]
